# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_pipeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61udio_pipeline.proto\x12\x0e\x61udio_pipeline\"\xa8\x01\n\nAudioChunk\x12\x12\n\nmeeting_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\r\n\x05track\x18\x03 \x01(\t\x12\x10\n\x08wav_data\x18\x04 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x05 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x06 \x01(\x05\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x03\x12\x10\n\x08sequence\x18\x08 \x01(\x05\"P\n\x13StreamAudioResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x17\n\x0f\x63hunks_received\x18\x03 \x01(\x05\x32h\n\x14\x41udioPipelineService\x12P\n\x0bStreamAudio\x12\x1a.audio_pipeline.AudioChunk\x1a#.audio_pipeline.StreamAudioResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=41
  _globals['_AUDIOCHUNK']._serialized_end=209
  _globals['_STREAMAUDIORESPONSE']._serialized_start=211
  _globals['_STREAMAUDIORESPONSE']._serialized_end=291
  _globals['_AUDIOPIPELINESERVICE']._serialized_start=293
  _globals['_AUDIOPIPELINESERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
