# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import feedback_ingestion_pb2 as feedback__ingestion__pb2


class FeedbackIngestionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishFeedback = channel.unary_unary(
                '/feedback_ingestion.FeedbackIngestionService/PublishFeedback',
                request_serializer=feedback__ingestion__pb2.PublishFeedbackRequest.SerializeToString,
                response_deserializer=feedback__ingestion__pb2.PublishFeedbackResponse.FromString,
                )


class FeedbackIngestionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeedbackIngestionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishFeedback,
                    request_deserializer=feedback__ingestion__pb2.PublishFeedbackRequest.FromString,
                    response_serializer=feedback__ingestion__pb2.PublishFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'feedback_ingestion.FeedbackIngestionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FeedbackIngestionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/feedback_ingestion.FeedbackIngestionService/PublishFeedback',
            feedback__ingestion__pb2.PublishFeedbackRequest.SerializeToString,
            feedback__ingestion__pb2.PublishFeedbackResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
